package proyecto_ajedrez;
import controlador.Controlador;

public class TABLA extends javax.swing.JFrame {

    /**
     * Creates new form PRUEBA
     */
    public TABLA() {
        initComponents();
        this.setSize(600, 600);
        this.setLocationRelativeTo(null);
        this.setTitle("AJEDREZ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        c10 = new javax.swing.JButton();
        c11 = new javax.swing.JButton();
        c12 = new javax.swing.JButton();
        c13 = new javax.swing.JButton();
        c14 = new javax.swing.JButton();
        c15 = new javax.swing.JButton();
        c16 = new javax.swing.JButton();
        c17 = new javax.swing.JButton();
        c18 = new javax.swing.JButton();
        c19 = new javax.swing.JButton();
        c20 = new javax.swing.JButton();
        c21 = new javax.swing.JButton();
        c22 = new javax.swing.JButton();
        c23 = new javax.swing.JButton();
        c24 = new javax.swing.JButton();
        c25 = new javax.swing.JButton();
        c26 = new javax.swing.JButton();
        c27 = new javax.swing.JButton();
        c28 = new javax.swing.JButton();
        c29 = new javax.swing.JButton();
        c30 = new javax.swing.JButton();
        c31 = new javax.swing.JButton();
        c32 = new javax.swing.JButton();
        c33 = new javax.swing.JButton();
        c34 = new javax.swing.JButton();
        c35 = new javax.swing.JButton();
        c36 = new javax.swing.JButton();
        c37 = new javax.swing.JButton();
        c38 = new javax.swing.JButton();
        c39 = new javax.swing.JButton();
        c40 = new javax.swing.JButton();
        c41 = new javax.swing.JButton();
        c42 = new javax.swing.JButton();
        c43 = new javax.swing.JButton();
        c44 = new javax.swing.JButton();
        c45 = new javax.swing.JButton();
        c46 = new javax.swing.JButton();
        c47 = new javax.swing.JButton();
        c48 = new javax.swing.JButton();
        c49 = new javax.swing.JButton();
        c50 = new javax.swing.JButton();
        c51 = new javax.swing.JButton();
        c52 = new javax.swing.JButton();
        c53 = new javax.swing.JButton();
        c54 = new javax.swing.JButton();
        c55 = new javax.swing.JButton();
        c56 = new javax.swing.JButton();
        c57 = new javax.swing.JButton();
        c58 = new javax.swing.JButton();
        c59 = new javax.swing.JButton();
        c60 = new javax.swing.JButton();
        c61 = new javax.swing.JButton();
        c62 = new javax.swing.JButton();
        c63 = new javax.swing.JButton();
        c64 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jButton21.setText("jButton21");

        jButton38.setText("jButton38");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(8, 8));

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/TORRE N.png"))); // NOI18N
        c1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c1);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CABALLO N.png"))); // NOI18N
        c2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c2);

        c3.setBackground(new java.awt.Color(0, 0, 0));
        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ALFIL N.png"))); // NOI18N
        c3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c3);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/REINA N.png"))); // NOI18N
        c4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c4);

        c5.setBackground(new java.awt.Color(0, 0, 0));
        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/REY N.png"))); // NOI18N
        c5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c5);

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ALFIL N.png"))); // NOI18N
        c6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c6);

        c7.setBackground(new java.awt.Color(0, 0, 0));
        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CABALLO N.png"))); // NOI18N
        c7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c7);

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/TORRE N.png"))); // NOI18N
        c8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c8.setContentAreaFilled(false);
        jPanel1.add(c8);

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c9);

        c10.setBackground(new java.awt.Color(0, 0, 0));
        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c10);

        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c11);

        c12.setBackground(new java.awt.Color(0, 0, 0));
        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c12);

        c13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c13);

        c14.setBackground(new java.awt.Color(0, 0, 0));
        c14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c14);

        c15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c15);

        c16.setBackground(new java.awt.Color(0, 0, 0));
        c16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON N.png"))); // NOI18N
        c16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c16);

        c17.setBackground(new java.awt.Color(0, 0, 0));
        c17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c17);

        c18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c18);

        c19.setBackground(new java.awt.Color(0, 0, 0));
        c19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c19);

        c20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c20);

        c21.setBackground(new java.awt.Color(0, 0, 0));
        c21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c21);

        c22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c22);

        c23.setBackground(new java.awt.Color(0, 0, 0));
        c23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c23);

        c24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c24);

        c25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c25);

        c26.setBackground(new java.awt.Color(0, 0, 0));
        c26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c26);

        c27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c27);

        c28.setBackground(new java.awt.Color(0, 0, 0));
        c28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c28);

        c29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c29);

        c30.setBackground(new java.awt.Color(0, 0, 0));
        c30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c30);

        c31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c31);

        c32.setBackground(new java.awt.Color(0, 0, 0));
        c32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c32);

        c33.setBackground(new java.awt.Color(0, 0, 0));
        c33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c33);

        c34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c34);

        c35.setBackground(new java.awt.Color(0, 0, 0));
        c35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c35);

        c36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c36);

        c37.setBackground(new java.awt.Color(0, 0, 0));
        c37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c37);

        c38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c38);

        c39.setBackground(new java.awt.Color(0, 0, 0));
        c39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c39);

        c40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c40);

        c41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c41);

        c42.setBackground(new java.awt.Color(0, 0, 0));
        c42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c42);

        c43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c43);

        c44.setBackground(new java.awt.Color(0, 0, 0));
        c44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c44);

        c45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c45);

        c46.setBackground(new java.awt.Color(0, 0, 0));
        c46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c46);

        c47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c47);

        c48.setBackground(new java.awt.Color(0, 0, 0));
        c48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c48);

        c49.setBackground(new java.awt.Color(0, 0, 0));
        c49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c49);

        c50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c50);

        c51.setBackground(new java.awt.Color(0, 0, 0));
        c51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c51);

        c52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c52);

        c53.setBackground(new java.awt.Color(0, 0, 0));
        c53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c53);

        c54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c54);

        c55.setBackground(new java.awt.Color(0, 0, 0));
        c55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c55);

        c56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/PEON B.png"))); // NOI18N
        c56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c56);

        c57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/TORRE B.png"))); // NOI18N
        c57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c57);

        c58.setBackground(new java.awt.Color(0, 0, 0));
        c58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CABALLO B.png"))); // NOI18N
        c58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c58);

        c59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ALFIL B.png"))); // NOI18N
        c59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c59);

        c60.setBackground(new java.awt.Color(0, 0, 0));
        c60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/REINA B.png"))); // NOI18N
        c60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c60);

        c61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/REY B.png"))); // NOI18N
        c61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c61);

        c62.setBackground(new java.awt.Color(0, 0, 0));
        c62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/ALFIL B.png"))); // NOI18N
        c62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c62);

        c63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/CABALLO B.png"))); // NOI18N
        c63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c63);

        c64.setBackground(new java.awt.Color(0, 0, 0));
        c64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/TORRE B.png"))); // NOI18N
        c64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(c64);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TABLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TABLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TABLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TABLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TABLA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton c1;
    public static javax.swing.JButton c10;
    public static javax.swing.JButton c11;
    public static javax.swing.JButton c12;
    public static javax.swing.JButton c13;
    public static javax.swing.JButton c14;
    public static javax.swing.JButton c15;
    public static javax.swing.JButton c16;
    public static javax.swing.JButton c17;
    public static javax.swing.JButton c18;
    public static javax.swing.JButton c19;
    public static javax.swing.JButton c2;
    public static javax.swing.JButton c20;
    public static javax.swing.JButton c21;
    public static javax.swing.JButton c22;
    public static javax.swing.JButton c23;
    public static javax.swing.JButton c24;
    public static javax.swing.JButton c25;
    public static javax.swing.JButton c26;
    public static javax.swing.JButton c27;
    public static javax.swing.JButton c28;
    public static javax.swing.JButton c29;
    public static javax.swing.JButton c3;
    public static javax.swing.JButton c30;
    public static javax.swing.JButton c31;
    public static javax.swing.JButton c32;
    public static javax.swing.JButton c33;
    public static javax.swing.JButton c34;
    public static javax.swing.JButton c35;
    public static javax.swing.JButton c36;
    public static javax.swing.JButton c37;
    public static javax.swing.JButton c38;
    public static javax.swing.JButton c39;
    public static javax.swing.JButton c4;
    public static javax.swing.JButton c40;
    public static javax.swing.JButton c41;
    public static javax.swing.JButton c42;
    public static javax.swing.JButton c43;
    public static javax.swing.JButton c44;
    public static javax.swing.JButton c45;
    public static javax.swing.JButton c46;
    public static javax.swing.JButton c47;
    public static javax.swing.JButton c48;
    public static javax.swing.JButton c49;
    public static javax.swing.JButton c5;
    public static javax.swing.JButton c50;
    public static javax.swing.JButton c51;
    public static javax.swing.JButton c52;
    public static javax.swing.JButton c53;
    public static javax.swing.JButton c54;
    public static javax.swing.JButton c55;
    public static javax.swing.JButton c56;
    public static javax.swing.JButton c57;
    public static javax.swing.JButton c58;
    public static javax.swing.JButton c59;
    public static javax.swing.JButton c6;
    public static javax.swing.JButton c60;
    public static javax.swing.JButton c61;
    public static javax.swing.JButton c62;
    public static javax.swing.JButton c63;
    public static javax.swing.JButton c64;
    public static javax.swing.JButton c7;
    public static javax.swing.JButton c8;
    public static javax.swing.JButton c9;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton38;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
